spring:
  application:
    name: MoneyMindfulBackend
  datasource:
    url: jdbc:mysql://db:3306/money_mindful?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: mm_user
    password: database_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  sql:
    init:
      platform: mysql
  security:
    user:
      name: admin
      password: secret

server:
  port: 8080

logging:
  level:
    root: ERROR
    org.springframework.web: DEBUG
    com.auth0.example: TRACE

jwt:
  secret: 'JWTSecretKey'
  expiration:
    time: 86400000 # 24 hours in milliseconds
